# Generated by Django 5.2.3 on 2025-06-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_community_post_communities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='communities',
            new_name='community',
        ),
    ]
