# Generated by Django 5.2.3 on 2025-06-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_communities_post_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.community'),
        ),
    ]
