# Generated by Django 5.2.3 on 2025-06-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_link_url_post_post_type_polloption_pollvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollvote',
            name='poll_option',
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
        migrations.DeleteModel(
            name='PollVote',
        ),
    ]
