# Generated by Django 5.2.3 on 2025-07-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_pollvote_poll_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
