# Generated by Django 5.2.4 on 2025-07-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_vote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(blank=True, choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4, null=True),
        ),
    ]
