# Generated by Django 5.2.4 on 2025-07-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_vote_vote_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_type',
        ),
    ]
