# Generated by Django 5.2.4 on 2025-07-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('vote', 'Vote'), ('follow', 'Follow'), ('mention', 'Mention')], max_length=20),
        ),
    ]
