# Generated by Django 5.2.3 on 2025-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
        migrations.AddField(
            model_name='post',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.community'),
        ),
    ]
