# Generated by Django 5.2.3 on 2025-07-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_post_language_botsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
    ]
