# Generated by Django 5.2.3 on 2025-07-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_language_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_weekly_helper',
            field=models.BooleanField(default=False),
        ),
    ]
