# Generated by Django 5.2.3 on 2025-08-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_loggedbug'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedbug',
            name='fixed_code',
            field=models.TextField(blank=True, help_text='The final version of the code after DevAlly fix.', null=True),
        ),
    ]
