# Generated by Django 5.2.3 on 2025-08-15 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(help_text='Topic created by Administrator', max_length=255)),
                ('title', models.CharField(help_text='Title of the challenge', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the challenge')),
                ('test_cases', models.JSONField(help_text="A list of test cases, e.g., [{'input': [1, 2], 'expected': 3}]")),
                ('solution_code', models.TextField(help_text='Suggested answer')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
