# Generated by Django 5.2.3 on 2025-08-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_weeklychallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklychallenge',
            name='language',
            field=models.CharField(default='python', help_text='Ngôn ngữ lập trình của challenge (python, javascript, etc.)', max_length=50),
        ),
    ]
