# Generated by Django 5.2.3 on 2025-08-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_weeklychallenge_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklychallenge',
            name='language',
            field=models.CharField(default='python', help_text='Programming language of weekly challenge (python, javascript, etc.)', max_length=50),
        ),
    ]
