# Generated by Django 5.2.3 on 2025-08-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_challengesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.challengesubmission'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('vote', 'Vote'), ('follow', 'Follow'), ('mention', 'Mention'), ('bot_analysis', 'Bot Analysis'), ('challenge_submission', 'Challenge Submission')], max_length=20),
        ),
    ]
