# Generated by Django 5.2.3 on 2025-08-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_notification_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('vote', 'Vote'), ('follow', 'Follow'), ('mention', 'Mention'), ('bot_analysis', 'Bot Analysis'), ('challenge_submission', 'Challenge Submission'), ('challenge_review', 'Challenge Review')], max_length=20),
        ),
    ]
